export const featured = [
  {
    id: 1,
    title: "Film Shop",
    img: "https://innazozulia-cv.vercel.app/images/img-13.png",
    technologies: "ReactJS, mockApi, SCSS",
    src: "https://react-filmcameras-qp3tmb2l3-innazozulia.vercel.app/",
  },
  {
    id: 2,
    title: "Xbox Game Store",
    img: "https://innazozulia-cv.vercel.app/images/img-17.png",
    technologies: "ReactJS, CSS, Redux",
    src: "https://react-game-store-qpysne1p0-innazozulia.vercel.app/",
  },
  {
    id: 3,
    title: "News Magazine",
    img: "https://innazozulia-cv.vercel.app/images/img-21.png",
    technologies: "ReactJS, modules CSS",
    src: "https://news-mazagine.vercel.app/",
  },
  {
    id: 4,
    title: "Food Delivery",
    img: "https://innazozulia-cv.vercel.app/images/img-5.png",
    technologies: "HTML, CSS, JS",
    src: "https://keen-mcnulty-c1e961.netlify.app/",
  },
  {
    id: 5,
    title: "Travel Shop",
    img: "https://innazozulia-cv.vercel.app/images/img-2.png",
    technologies: "HTML, CSS, JS",
    src: "https://gracious-payne-b77063.netlify.app/",
  },
  {
    id: 6,
    title: "Building Company",
    img: "https://innazozulia-cv.vercel.app/images/img-3.png",
    technologies: "HTML, CSS, JS",
    src: "https://blissful-bassi-64255f.netlify.app/",
  },

  // {
  //   id: 7,
  //   title: "Grocery Shop",
  //   img: "https://innazozulia-cv.vercel.app/images/img-9.png",
  //   technologies: "HTML, CSS, JS",
  //   src: "https://sleepy-panini-1b4076.netlify.app/home.html",
  // },
  // {
  //   id: 8,
  //   title: "Bird Social Media",
  //   img: "assets/social.png",
  //   technologies: "NodeJS, Express, ReactJS, MySQL",
  //   scr: "https://github.com/innazozulia/BirdSocialMedia-ReactJS-NodeJS-MySQL-",
  // },
];

export const layout = [
  {
    id: 1,
    title: "Food Delivery",
    img: "https://innazozulia-cv.vercel.app/images/img-5.png",
    technologies: "HTML, CSS, JS",
    src: "https://keen-mcnulty-c1e961.netlify.app/",
  },
  {
    id: 2,
    title: "Travel Shop",
    img: "https://innazozulia-cv.vercel.app/images/img-2.png",
    technologies: "HTML, CSS, JS",
    src: "https://gracious-payne-b77063.netlify.app/",
  },
  {
    id: 3,
    title: "Building Company",
    img: "https://innazozulia-cv.vercel.app/images/img-3.png",
    technologies: "HTML, CSS, JS",
    src: "https://blissful-bassi-64255f.netlify.app/",
  },
  {
    id: 4,
    title: "Servers Presentation",
    img: "https://innazozulia-cv.vercel.app/images/img-4.png",
    technologies: "HTML, CSS, JS",
    src: "https://startling-chimera-271f1c.netlify.app/",
  },
  {
    id: 5,
    title: "Design Agency",
    img: "https://innazozulia-cv.vercel.app/images/img-1.png",
    technologies: "HTML, CSS, JS",
    src: "https://festive-hopper-896958.netlify.app/",
  },
  {
    id: 6,
    title: "IBM Webinar",
    img: "https://innazozulia-cv.vercel.app/images/img-6.png",
    technologies: "HTML, CSS, JS",
    src: "https://adoring-wright-5c2ff1.netlify.app/",
  },
  // {
  //   id: 7,
  //   title: "Medical Clinic",
  //   img: "https://innazozulia-cv.vercel.app/images/img-7.png",
  //   technologies: "HTML, CSS, JS",
  //   src: "https://cranky-heisenberg-5409e8.netlify.app/",
  // },
  // {
  //   id: 8,
  //   title: "Grocery Shop",
  //   img: "https://innazozulia-cv.vercel.app/images/img-9.png",
  //   technologies: "HTML, CSS, JS",
  //   src: "https://sleepy-panini-1b4076.netlify.app/home.html",
  // },
  // {
  //   id: 9,
  //   title: "Tech Provider",
  //   img: "https://innazozulia-cv.vercel.app/images/img-8.png",
  //   technologies: "HTML, CSS, JS",
  //   src: "https://superlative-creponne-76c22a.netlify.app/",
  // },
];

export const reactjs = [
  {
    id: 1,
    title: "Film Shop",
    img: "https://innazozulia-cv.vercel.app/images/img-13.png",
    technologies: "ReactJS, mockApi, SCSS",
    src: "https://react-filmcameras-qp3tmb2l3-innazozulia.vercel.app/",
  },
  {
    id: 2,
    title: "Xbox Game Store",
    img: "https://innazozulia-cv.vercel.app/images/img-17.png",
    technologies: "ReactJS, CSS, Redux",
    src: "https://react-game-store-qpysne1p0-innazozulia.vercel.app/",
  },
  {
    id: 3,
    title: "News Magazine",
    img: "https://innazozulia-cv.vercel.app/images/img-21.png",
    technologies: "ReactJS, modules CSS",
    src: "https://news-mazagine.vercel.app/",
  },
  {
    id: 4,
    title: "Draggable To Do",
    img: "https://innazozulia-cv.vercel.app/images/img-12.png",
    technologies: "ReactJS, CSS",
    src: "https://draggable-react-to-do.vercel.app/",
  },
  {
    id: 5,
    title: "Bakery & Delivery",
    img: "https://innazozulia-cv.vercel.app/images/img-14.png",
    technologies: "ReactJS, Redux-Toolkit",
    src: "https://react-deliveroo.vercel.app/?sortProperty=rating&category=0&currentPage=1",
  },
  {
    id: 6,
    title: "Booking",
    img: "assets/booking.png",
    technologies: "ReactJS, mockApi, SCSS",
    src: "https://your-booking-4t4ipfsi2-innazozulia.vercel.app/",
  },
  // {
  //   id: 7,
  //   title: "E-commerce",
  //   img: "assets/ecom.png",
  //   technologies: "ReactJS, SCSS",
  //   src: "",
  // },
];
export const fullstack = [
  {
    id: 1,
    title: "techNotes",
    img: "assets/technotes.png",
    technologies: "NodeJS, Express, ReactJS, MongoDB",
    src: "https://github.com/innazozulia/MERN_techNotes",
  },
  {
    id: 2,
    title: "Bird Social Media",
    img: "assets/social.png",
    technologies: "NodeJS, Express, ReactJS, MySQL",
    src: "https://github.com/innazozulia/BirdSocialMedia-ReactJS-NodeJS-MySQL-",
  },
  {
    id: 3,
    title: "News Magazine",
    img: "assets/articles.png",
    technologies: "NodeJS, Express, ReactJS, MySQL",
    src: "https://github.com/innazozulia/MagazineWithArticlesReactJsExpressMySql",
  },
  {
    id: 4,
    title: "My books",
    img: "assets/books.png",
    technologies: "NodeJS, Express, ReactJS, MongoDB",
    src: "https://github.com/innazozulia-zz/MERNBookTracker",
  },
  {
    id: 5,
    title: "Blog",
    img: "assets/article.png",
    technologies: "NodeJS, Express, ReactJS, MongoDB",
    src: "https://github.com/innazozulia/MagazineWithArticlesReactJsExpressMySql",
  },
];

export const sliderItems = [
  {
    id: 1,
    img: "assets/films.png",
    title: "Film Shop",
    src: "https://react-filmcameras-qp3tmb2l3-innazozulia.vercel.app/",
    bg: "f5fafd",
  },
  {
    id: 2,
    img: "assets/game.png",
    title: "Xbox Game Store",
    src: "https://react-game-store-qpysne1p0-innazozulia.vercel.app/",
    bg: "fcf1ed",
  },
  {
    id: 3,
    img: "assets/booking.png",
    title: "Booking",
    src: "https://your-booking-4t4ipfsi2-innazozulia.vercel.app/",
    bg: "fbf0f4",
  },
  {
    id: 4,
    img: "assets/blog.png",
    title: "News Magazine",
    src: "https://news-mazagine.vercel.app/",
    bg: "f5fafd",
  },
  {
    id: 5,
    img: "assets/social.png",
    title: "Social Media",
    src: "https://github.com/innazozulia/BirdSocialMedia-ReactJS-NodeJS-MySQL-",
    bg: "fcf1ed",
  },
  {
    id: 6,
    img: "assets/delivero.png",
    title: "French Bakery",
    src: "https://react-deliveroo.vercel.app/?sortProperty=rating&category=0&currentPage=1",
    bg: "f5fafd",
  },
];
